// ============================================================================
// SUPABASE DATABASE TYPES (Generated by Supabase CLI)
// ============================================================================
import type { Database } from './supabase';

export type Business = Database['public']['Tables']['businesses']['Row'];
export type Customer = Database['public']['Tables']['customers']['Row'];
export type WaitlistEntry = Database['public']['Tables']['waitlist_entries']['Row'];
export type Table = Database['public']['Tables']['tables']['Row'];

export type WaitlistStatus = 'WAITING' | 'CONFIRMED' | 'NOTIFIED' | 'SEATED' | 'CANCELLED' | 'NO_SHOW';

// ============================================================================
// REQUEST/RESPONSE TYPES
// ============================================================================

export interface ChatRequest {
  phone: string;
  message: string;
  businessId: string;
  context?: BusinessContext;
}

export interface ChatResponse {
  response: string;
  actions: Action[];
  confidence: number;
}

export interface IntentRequest {
  message: string;
  context?: Partial<BusinessContext>;
}

export interface IntentResponse {
  intent: IntentType;
  entities: Record<string, any>;
  confidence: number;
}

export interface BatchRequest {
  messages: Array<{
    phone: string;
    message: string;
    businessId: string;
    context?: BusinessContext;
  }>;
}

export interface BatchResponse {
  results: Array<{
    index: number;
    success: boolean;
    data?: ChatResponse;
    error?: string;
  }>;
  processedCount: number;
  failedCount: number;
}

export interface HealthResponse {
  status: 'healthy' | 'degraded' | 'unhealthy';
  ollama: boolean;
  redis: boolean;
  model: string;
  uptime: number;
  timestamp: string;
}

// Action Types
export type ActionType =
  | 'REGISTER'
  | 'CHECK_STATUS'
  | 'CANCEL'
  | 'INFO_REQUEST'
  | 'UNKNOWN';

export interface Action {
  type: ActionType;
  data: Record<string, any>;
  confidence?: number;
}

// Agent System Types
export interface AgentActionDefinition {
  type: string;
  keywords: string[];
  description: string;
  priority?: number;
}

export interface AgentConfig {
  id: string;
  name: string;
  description: string;
  model: string;
  systemPrompt: string;
  actions?: AgentActionDefinition[];
  temperature?: number;
  maxTokens?: number;
  numCtx?: number;
  enabled?: boolean;
}

export interface AgentResponse {
  response: string;
  action?: string | null;
  conversationId?: string;
  agent: {
    id: string;
    name: string;
  };
  tokenCount?: number;
  processingTime?: number;
}

export interface AgentListItem {
  id: string;
  name: string;
  description: string;
  enabled: boolean;
  actions?: Array<{
    type: string;
    description: string;
  }>;
}

// Intent Types
export type IntentType =
  | 'register'
  | 'query_status'
  | 'cancel'
  | 'request_info'
  | 'general_question'
  | 'greeting'
  | 'unknown';

// Business hours schema stored in businesses.weekly_hours (JSONB)
export interface WeeklyHoursShift {
  open: string;  // "HH:mm" in local Buenos Aires time
  close: string; // "HH:mm" — may be past midnight (e.g. "02:00" = 02:00 next day)
}
export interface WeeklyHoursDayEntry {
  closed: boolean;
  shifts: WeeklyHoursShift[];
}
export type WeeklyHoursDayKey = 'mon' | 'tue' | 'wed' | 'thu' | 'fri' | 'sat' | 'sun';
export type WeeklyHours = Partial<Record<WeeklyHoursDayKey, WeeklyHoursDayEntry>>;

// Business Context
export interface BusinessContext {
  businessName: string;
  businessAddress?: string;
  businessHours?: string;
  weeklyHours?: WeeklyHours;
  currentWaitlist: number;
  averageWaitTime: number;
  customerInfo?: CustomerInfo;
  additionalInfo?: Record<string, any>;
}

export interface CustomerInfo {
  isKnown: boolean;
  name?: string;
  previousVisits?: number;
  lastVisit?: string;
  preferences?: string[];
}

// Conversation Types
export interface ConversationMessage {
  role: 'user' | 'assistant' | 'system';
  content: string;
  timestamp: number;
}

export interface ConversationHistory {
  phone: string;
  messages: ConversationMessage[];
  lastUpdated: number;
}

// Ollama Types
export interface OllamaMessage {
  role: 'system' | 'user' | 'assistant';
  content: string;
}

export interface OllamaGenerationOptions {
  temperature?: number;
  top_p?: number;
  num_predict?: number;
  num_ctx?: number;
}

export interface OllamaRequest {
  model: string;
  messages: OllamaMessage[];
  stream?: boolean;
  options?: OllamaGenerationOptions;
}

export interface OllamaResponse {
  model: string;
  message: {
    role: string;
    content: string;
  };
  done: boolean;
  total_duration?: number;
  load_duration?: number;
  prompt_eval_count?: number;
  eval_count?: number;
}

// Error Types
export interface ApiError {
  code: string;
  message: string;
  details?: any;
}

// Cache Types
export interface CachedBusinessContext extends BusinessContext {
  cachedAt: number;
  expiresAt: number;
}

// Environment Variables
export interface EnvConfig {
  port: number;
  nodeEnv: string;
  ollamaBaseUrl: string;
  ollamaModel: string;
  ollamaTimeout: number;
  apiKey: string;
  allowedOrigins: string[];
  redisUrl: string;
  logLevel: string;
  supabaseUrl?: string;
  supabaseKey?: string; useHttps: boolean;
  sslKeyPath?: string;
  sslCertPath?: string;
}

// Baileys Session Types
export interface BaileysSession {
  businessId: string;
  sessionPath: string;
  isConnected: boolean;
  qrCode?: string;
  lastActivity?: number;
}

export interface BaileysMessage {
  from: string;
  message: string;
  timestamp: number;
  businessId: string;
  messageId?: string;
  fromMe?: boolean;
}

// WebSocket Event Types
export type WebSocketEventType =
  | 'qr_generated'
  | 'session_ready'
  | 'session_error'
  | 'session_disconnected'
  | 'message_received'
  | 'reservation_created'
  | 'reservation_updated';

export interface WebSocketEvent {
  type: WebSocketEventType;
  businessId: string;
  data: any;
  timestamp: number;
}

export interface QRGeneratedEvent {
  qrCode: string;
  businessId: string;
  expiresIn?: number;
}

export interface SessionReadyEvent {
  businessId: string;
  phoneNumber?: string;
  message: string;
}

export interface ReservationCreatedEvent {
  waitlistEntry: WaitlistEntry;
  customer: Customer;
  table?: Table;
  message: string;
}

// Represents a row from business_blocked_dates as seen by the conversation flow.
// Both fields can be null: `reason` when no internal note was given; `reasonMessage`
// when the AI-generated client-facing message hasn't been produced yet.
export type BlockedDateEntry = {
  reason: string | null;
  reasonMessage: string | null;
};

// Reservation Flow Types
export interface ReservationDraft {
  conversationId: string;
  businessId: string;
  customerName?: string;
  partySize?: number;
  step:
    | 'name'
    | 'party_size'
    | 'schedule_choice'
    | 'date'
    | 'time'
    | 'confirm_slot'
    | 'confirm_summary'
    | 'summary_edit_menu'
    | 'cancel_menu'
    | 'cancel_confirm'
    | 'completed'
    | 'edit_menu';
  // Scheduling fields (day/time chosen within the next 7 days; absent = instant/turno actual)
  scheduledDate?: string; // YYYY-MM-DD, Buenos Aires local day
  scheduledTime?: string; // HH:mm, 24h
  scheduledAt?: string; // ISO UTC instant combining scheduledDate + scheduledTime
  // confirm_slot step: which step triggered the suggestion (to know where to go back on "no")
  confirmSlotOrigin?: 'schedule_choice' | 'time';
  // party_size step: true right after asking "¿Cuál es tu nombre correcto?" — the
  // next reply should be treated as the name itself, not as a party size answer.
  awaitingNameCorrection?: boolean;
  // Set when the customer names a weekday that resolves to TODAY (e.g. "el
  // jueves" said on a Thursday) — genuinely ambiguous between "today" and
  // "next week". Holds both candidate dates (and any time already given in
  // the same message) until the customer confirms which one they meant.
  pendingWeekdayDisambiguation?: {
    weekdayLabel: string; // e.g. "jueves" — used to phrase the question
    todayDateKey: string; // YYYY-MM-DD
    nextDateKey: string; // YYYY-MM-DD, exactly 7 days later
    pendingHour?: number;
    pendingMinute?: number;
  };
  // Set when the customer names a weekday together with an explicit
  // day-of-month number that doesn't match the nearest in-window occurrence
  // of that weekday (e.g. "jueves 17" when the closest bookable Thursday is
  // the 9th) — the requested date is beyond the 7-day booking window. Holds
  // the nearest in-window alternative (and any time already given in the
  // same message) until the customer confirms whether to take it instead.
  pendingWeekdayDayMismatch?: {
    weekdayLabel: string; // e.g. "jueves"
    requestedDayNumber: number; // e.g. 17
    nearestDateKey: string; // YYYY-MM-DD, nearest in-window occurrence
    nearestLabel: string; // e.g. "jueves 09/07"
    nearestIsToday: boolean;
    pendingHour?: number;
    pendingMinute?: number;
  };
  // Set right after the customer chooses "hoy (turno actual)" while the
  // business is currently open — asks for the specific hour instead of
  // jumping straight to an instant reservation. Holds today's date key and
  // the current shift's closing time (for display) until the customer
  // answers with an hour, or "ahora" to keep the instant behavior.
  pendingTodayTimeChoice?: {
    dateKey: string; // YYYY-MM-DD, today
    closeLabel: string | null; // e.g. "23:00" — current shift's effective closing time
  };
  // Edit mode fields
  editMode?: boolean;
  editingField?: 'party_size' | 'schedule' | 'date' | 'time';
  existingReservationId?: string;
  // confirm_summary: after editing a field from the summary menu, return to the
  // summary instead of continuing the normal step progression.
  returnToSummary?: boolean;
  // Invalid attempt tracking (for exit-on-repeat)
  invalidAttempts?: number;
  createdAt: number;
  updatedAt: number;
}

export interface CreateReservationRequest {
  businessId: string;
  customerName: string;
  customerPhone: string;
  partySize: number;
  tableId?: string;
  source?: 'AI_CHAT' | 'DASHBOARD';
  /** ISO UTC instant for a future day/time within the next 7 days; omitted/null = instant reservation for the current turn. */
  scheduledAt?: string | null;
}

export interface CreateReservationResponse {
  success: boolean;
  waitlistEntry?: WaitlistEntry;
  error?: string;
  /** True when a valid reservation already exists for this customer today */
  alreadyExists?: boolean;
  /**
   * Present when creation was rejected by a business-configured date block
   * (business_blocked_dates or future_reservations_blocked_for_date) — a
   * ready-to-send Spanish message for the customer, relayed as-is.
   */
  blockedMessage?: string;
}
