// ============================================================================
// SUPABASE DATABASE TYPES (Generated by Supabase CLI)
// ============================================================================
import type { Database } from './supabase.js';

export type Business = Database['public']['Tables']['businesses']['Row'];
export type Customer = Database['public']['Tables']['customers']['Row'];
export type WaitlistEntry = Database['public']['Tables']['waitlist_entries']['Row'];
export type Table = Database['public']['Tables']['tables']['Row'];

export type WaitlistStatus = 'WAITING' | 'CONFIRMED' | 'NOTIFIED' | 'SEATED' | 'CANCELLED' | 'NO_SHOW';

// ============================================================================
// REQUEST/RESPONSE TYPES
// ============================================================================

export interface ChatRequest {
  phone: string;
  message: string;
  businessId: string;
  context?: BusinessContext;
}

export interface ChatResponse {
  response: string;
  actions: Action[];
  confidence: number;
}

export interface IntentRequest {
  message: string;
  context?: Partial<BusinessContext>;
}

export interface IntentResponse {
  intent: IntentType;
  entities: Record<string, any>;
  confidence: number;
}

export interface BatchRequest {
  messages: Array<{
    phone: string;
    message: string;
    businessId: string;
    context?: BusinessContext;
  }>;
}

export interface BatchResponse {
  results: Array<{
    index: number;
    success: boolean;
    data?: ChatResponse;
    error?: string;
  }>;
  processedCount: number;
  failedCount: number;
}

export interface HealthResponse {
  status: 'healthy' | 'degraded' | 'unhealthy';
  llm: boolean;
  redis: boolean;
  model: string;
  uptime: number;
  timestamp: string;
}

// Action Types
export type ActionType =
  | 'REGISTER'
  | 'CHECK_STATUS'
  | 'CANCEL'
  | 'INFO_REQUEST'
  | 'UNKNOWN';

export interface Action {
  type: ActionType;
  data: Record<string, any>;
  confidence?: number;
}

// Agent System Types
export interface AgentActionDefinition {
  type: string;
  keywords: string[];
  description: string;
  priority?: number;
}

export interface AgentConfig {
  id: string;
  name: string;
  description: string;
  model: string;
  systemPrompt: string;
  actions?: AgentActionDefinition[];
  temperature?: number;
  maxTokens?: number;
  /** See {@link LlmGenerationOptions.reasoningMaxTokens}. */
  reasoningMaxTokens?: number;
  numCtx?: number;
  enabled?: boolean;
}

export interface AgentResponse {
  response: string;
  action?: string | null;
  conversationId?: string;
  agent: {
    id: string;
    name: string;
  };
  tokenCount?: number;
  processingTime?: number;
}

export interface AgentListItem {
  id: string;
  name: string;
  description: string;
  enabled: boolean;
  actions?: Array<{
    type: string;
    description: string;
  }>;
}

// Intent Types
export type IntentType =
  | 'register'
  | 'query_status'
  | 'cancel'
  | 'request_info'
  | 'general_question'
  | 'greeting'
  | 'unknown';

// Business hours schema stored in businesses.weekly_hours (JSONB)
export interface WeeklyHoursShift {
  open: string;  // "HH:mm" in local Buenos Aires time
  close: string; // "HH:mm" — may be past midnight (e.g. "02:00" = 02:00 next day)
}
export interface WeeklyHoursDayEntry {
  closed: boolean;
  shifts: WeeklyHoursShift[];
}
export type WeeklyHoursDayKey = 'mon' | 'tue' | 'wed' | 'thu' | 'fri' | 'sat' | 'sun';
export type WeeklyHours = Partial<Record<WeeklyHoursDayKey, WeeklyHoursDayEntry>>;

// Business Context
export interface BusinessContext {
  businessName: string;
  businessAddress?: string;
  businessHours?: string;
  weeklyHours?: WeeklyHours;
  currentWaitlist: number;
  averageWaitTime: number;
  customerInfo?: CustomerInfo;
  additionalInfo?: Record<string, any>;
}

export interface CustomerInfo {
  isKnown: boolean;
  name?: string;
  previousVisits?: number;
  lastVisit?: string;
  preferences?: string[];
}

// Conversation Types
export interface ConversationMessage {
  role: 'user' | 'assistant' | 'system';
  content: string;
  timestamp: number;
}

export interface ConversationHistory {
  phone: string;
  messages: ConversationMessage[];
  lastUpdated: number;
}

// LLM (OpenRouter) Types

/**
 * Mensaje de texto plano — el caso que ya existía y sigue siendo el 95% de los
 * call sites (`{ role: 'user', content: '...' }`).
 */
export interface LlmTextMessage {
  role: 'system' | 'user' | 'assistant';
  content: string;
}

/**
 * Respuesta del assistant que pidió ejecutar herramientas. Se empuja al
 * historial TAL CUAL vino del modelo antes de los `LlmToolResultMessage`
 * correspondientes: OpenRouter valida que cada `tool_call_id` de un mensaje
 * `tool` tenga su `tool_calls[].id` en el assistant inmediatamente anterior.
 *
 * `content` puede venir null cuando el modelo sólo llamó herramientas sin
 * texto acompañante — es el caso normal, no un error.
 */
export interface LlmAssistantToolCallMessage {
  role: 'assistant';
  content: string | null;
  tool_calls: LlmToolCall[];
}

/**
 * Resultado de UNA herramienta, devuelto al modelo. `content` es siempre
 * string: el JSON del resultado va serializado (OpenRouter no acepta objetos
 * acá). `tool_call_id` debe coincidir con el id que emitió el modelo.
 */
export interface LlmToolResultMessage {
  role: 'tool';
  tool_call_id: string;
  /** Nombre de la función. Opcional en el spec, pero ayuda a los modelos a alinear resultados. */
  name?: string;
  content: string;
}

export type LlmMessage = LlmTextMessage | LlmAssistantToolCallMessage | LlmToolResultMessage;

export interface LlmGenerationOptions {
  temperature?: number;
  top_p?: number;
  maxTokens?: number;
  /**
   * Caps the model's internal reasoning/"thinking" tokens (OpenRouter's unified
   * `reasoning.max_tokens`). Reasoning models like google/gemini-2.5-pro draw
   * thinking tokens from the same `maxTokens` budget by default and can consume
   * nearly all of it unpredictably, truncating the visible reply mid-sentence —
   * this bounds that so the visible answer always has room.
   */
  reasoningMaxTokens?: number;
  /**
   * Se envía como `session_id` (sticky routing de OpenRouter). Fijarlo al
   * conversationId mantiene todas las iteraciones de un turno — y los turnos
   * sucesivos de la misma conversación — en el mismo proveedor, que es la
   * condición para que el prompt caching acierte.
   */
  sessionId?: string;
}

export interface LlmToolDefinition {
  type: 'function';
  function: {
    name: string;
    description: string;
    parameters: Record<string, any>;
  };
}

export interface LlmToolCall {
  id: string;
  type: 'function';
  function: {
    name: string;
    arguments: string; // JSON string, must be JSON.parse'd
  };
}

export interface OpenRouterChatCompletionRequest {
  model: string;
  models?: string[]; // fallback routing: tried in order if the primary is unavailable
  messages: LlmMessage[];
  temperature?: number;
  top_p?: number;
  max_tokens?: number;
  reasoning?: { max_tokens?: number };
  tools?: LlmToolDefinition[];
  tool_choice?: 'auto' | 'none' | { type: 'function'; function: { name: string } };
  /**
   * false obliga al modelo a pedir una herramienta por vez. Lo dejamos en true
   * (default de OpenRouter): el orquestador ejecuta el batch en paralelo y
   * devuelve todos los resultados juntos, que es lo que hace que "cancelá la
   * del viernes y creá una para mañana" se resuelva en un solo turno.
   */
  parallel_tool_calls?: boolean;
  /**
   * Sticky routing de OpenRouter: fija el mismo endpoint de proveedor entre
   * requests de una misma conversación para que el prompt caching acierte.
   * Sin esto cada iteración del loop puede caer en otro proveedor y perder el
   * prefijo cacheado.
   */
  session_id?: string;
}

export interface OpenRouterChatCompletionResponse {
  id: string;
  model: string;
  choices: Array<{
    message: {
      role: string;
      content: string | null;
      tool_calls?: LlmToolCall[];
    };
    finish_reason: string;
  }>;
  usage?: {
    prompt_tokens: number;
    completion_tokens: number;
    total_tokens: number;
  };
}

// Error Types
export interface ApiError {
  code: string;
  message: string;
  details?: any;
}

// Cache Types
export interface CachedBusinessContext extends BusinessContext {
  cachedAt: number;
  expiresAt: number;
}

// Environment Variables
export interface EnvConfig {
  port: number;
  nodeEnv: string;
  openRouterApiKey: string;
  openRouterModel: string;
  openRouterFallbackModels: string[];
  openRouterTimeout: number;
  openRouterSiteUrl?: string;
  openRouterSiteName?: string;
  apiKey: string;
  allowedOrigins: string[];
  redisUrl: string;
  logLevel: string;
  supabaseUrl?: string;
  /** 'v1' = flujo determinista; 'v2' = orquestador con tool-calling (ver src/agent/). */
  agentMode: 'v1' | 'v2';
  /** Lista blanca de comercios en v2 mientras el modo global sigue en v1. */
  agentV2BusinessIds: string[];
  /** Comercios donde v2 corre en sombra: v1 responde, v2 se computa y se loguea. */
  agentShadowBusinessIds: string[];
  supabaseKey?: string; useHttps: boolean;
  sslKeyPath?: string;
  sslCertPath?: string;
}

// Baileys Session Types
export interface BaileysSession {
  businessId: string;
  sessionPath: string;
  isConnected: boolean;
  qrCode?: string;
  lastActivity?: number;
}

export interface BaileysMessage {
  from: string;
  message: string;
  timestamp: number;
  businessId: string;
  messageId?: string;
  fromMe?: boolean;
}

// WebSocket Event Types
export type WebSocketEventType =
  | 'qr_generated'
  | 'session_ready'
  | 'session_error'
  | 'session_disconnected'
  | 'message_received'
  | 'reservation_created'
  | 'reservation_updated';

export interface WebSocketEvent {
  type: WebSocketEventType;
  businessId: string;
  data: any;
  timestamp: number;
}

export interface QRGeneratedEvent {
  qrCode: string;
  businessId: string;
  expiresIn?: number;
}

export interface SessionReadyEvent {
  businessId: string;
  phoneNumber?: string;
  message: string;
}

export interface ReservationCreatedEvent {
  waitlistEntry: WaitlistEntry;
  customer: Customer;
  table?: Table;
  message: string;
}

// Represents a row from business_blocked_dates as seen by the conversation flow.
// Both fields can be null: `reason` when no internal note was given; `reasonMessage`
// when the AI-generated client-facing message hasn't been produced yet.
export type BlockedDateEntry = {
  reason: string | null;
  reasonMessage: string | null;
};

/**
 * Evento publicado por el comercio. El agente los ofrece como opción extra en
 * el paso `schedule_choice`, además de "hoy" y "otra fecha".
 *
 * A diferencia de una reserva normal, un evento puede caer fuera de la ventana
 * de 7 días y su fecha se considera habilitada aunque el comercio no abra ese
 * día o lo tenga bloqueado: publicarlo ES la habilitación.
 */
export interface BusinessEvent {
  id: string;
  title: string;
  description: string | null;
  /** ISO UTC del inicio del evento. Se copia tal cual a waitlist_entries.scheduled_at. */
  startsAt: string;
  /** URLs públicas, máximo 3. Se envían por WhatsApp al elegir el evento. */
  imageUrls: string[];
}

// Reservation Flow Types
export interface ReservationDraft {
  conversationId: string;
  businessId: string;
  customerName?: string;
  /**
   * Apellido — optional. Set when the customer gives it together with their
   * name (e.g. "Matías Andrada") in the `name` step; left unset when they
   * only give a first name. Combined with customerName for the reservation
   * detail, but greetings/prompts always address the customer by first name.
   */
  customerLastName?: string;
  partySize?: number;
  step:
    | 'name'
    // Legacy: the `name` step no longer transitions here (apellido is never
    // asked separately). Kept only so drafts already at this step when this
    // shipped can still complete instead of getting stuck mid-flow.
    | 'last_name'
    | 'party_size'
    | 'schedule_choice'
    | 'date'
    | 'time'
    | 'confirm_slot'
    | 'confirm_summary'
    | 'summary_edit_menu'
    | 'cancel_menu'
    | 'cancel_confirm'
    | 'reservation_selection'
    | 'completed'
    | 'edit_menu'
    | 'edit_customer_name';
  // edit_customer_name step: which part of the stored name is being changed.
  nameEditField?: 'full' | 'lastName';
  // Reservation selection state for multiple active reservations.
  availableReservationIds?: string[];
  // What to do once the customer picks one of several active reservations:
  // open the edit menu (default) or go straight to the cancel menu.
  pendingSelectionAction?: 'edit' | 'cancel';
  // Scheduling fields (day/time chosen within the next 7 days; absent = instant/turno actual)
  scheduledDate?: string; // YYYY-MM-DD, Buenos Aires local day
  scheduledTime?: string; // HH:mm, 24h
  scheduledAt?: string; // ISO UTC instant combining scheduledDate + scheduledTime
  // Set when the customer picked one of the business's events at the
  // `schedule_choice` step. `scheduledAt` then mirrors the event's start, and
  // the reservation is created against that event (always pending approval).
  eventId?: string;
  eventTitle?: string;
  /**
   * Evento nombrado directamente en un mensaje donde el nombre del cliente
   * todavía no se conocía (ej. "Noche de sushi para 3" como primer mensaje).
   * A diferencia de `eventId`, esto NO significa que la reserva ya quede
   * asociada al evento — `scheduledAt`/`scheduledDate`/`scheduledTime` siguen
   * sin fijar. Se resuelve en `resolveEmbeddedScheduleOrPromptChoice` apenas
   * el nombre (y la cantidad de personas) estén confirmados, momento en el
   * que recién se aplica vía `applyEventChoice` y se completan esos campos.
   */
  pendingEventId?: string;
  pendingEventTitle?: string;
  /**
   * Snapshot of the menu last shown at `schedule_choice`, so the number the
   * customer replies with can be mapped back to what they actually saw. The
   * menu is dynamic: "Hoy" disappears when today has no availability left, and
   * the event entries vary per business, so the numbering can't be hardcoded.
   */
  scheduleChoiceOptions?: {
    includeToday: boolean;
    /**
     * Los eventos tal como se listaron, en orden. Se guarda el título junto al
     * id porque si el comercio desactiva un evento entre turnos hay que poder
     * nombrarlo al avisar que ya no está disponible, y para entonces la
     * consulta a la base ya no lo devuelve.
     */
    events: { id: string; title: string }[];
  };
  // confirm_slot step: which step triggered the suggestion (to know where to go back on "no")
  confirmSlotOrigin?: 'schedule_choice' | 'time' | 'date';
  // party_size step: true right after asking "¿Cuál es tu nombre correcto?" — the
  // next reply should be treated as the name itself, not as a party size answer.
  awaitingNameCorrection?: boolean;
  /**
   * Set together with `step: 'name'` right after sending the language menu.
   * Deliberately a transient flag and NOT a step of its own: the selection is
   * non-blocking, so if the next reply isn't a language choice it falls through
   * to the normal name parsing and the flow continues uninterrupted. Same
   * pattern as `awaitingNameCorrection` at the `party_size` step.
   */
  awaitingLanguageChoice?: boolean;
  // Set when the customer names a weekday that resolves to TODAY (e.g. "el
  // jueves" said on a Thursday) — genuinely ambiguous between "today" and
  // "next week". Holds both candidate dates (and any time already given in
  // the same message) until the customer confirms which one they meant.
  pendingWeekdayDisambiguation?: {
    weekdayLabel: string; // e.g. "jueves" — used to phrase the question
    todayDateKey: string; // YYYY-MM-DD
    nextDateKey: string; // YYYY-MM-DD, exactly 7 days later
    pendingHour?: number;
    pendingMinute?: number;
  };
  // Set when the customer names a weekday together with an explicit
  // day-of-month number that doesn't match the nearest in-window occurrence
  // of that weekday (e.g. "jueves 17" when the closest bookable Thursday is
  // the 9th) — the requested date is beyond the 7-day booking window. Holds
  // the nearest in-window alternative (and any time already given in the
  // same message) until the customer confirms whether to take it instead.
  pendingWeekdayDayMismatch?: {
    weekdayLabel: string; // e.g. "jueves"
    requestedDayNumber: number; // e.g. 17
    nearestDateKey: string; // YYYY-MM-DD, nearest in-window occurrence
    nearestLabel: string; // e.g. "jueves 09/07"
    nearestIsToday: boolean;
    pendingHour?: number;
    pendingMinute?: number;
  };
  // Set right after the customer chooses "hoy (turno actual)" while the
  // business is currently open — asks for the specific hour instead of
  // jumping straight to an instant reservation. Holds today's date key and
  // the current shift's closing time (for display) until the customer
  // answers with an hour, or "ahora" to keep the instant behavior.
  pendingTodayTimeChoice?: {
    dateKey: string; // YYYY-MM-DD, today
    closeLabel: string | null; // e.g. "23:00" — current shift's effective closing time
  };
  // Edit mode fields
  editMode?: boolean;
  editingField?: 'party_size' | 'schedule' | 'date' | 'time';
  existingReservationId?: string;
  // confirm_summary: after editing a field from the summary menu, return to the
  // summary instead of continuing the normal step progression.
  returnToSummary?: boolean;
  // Invalid attempt tracking (for exit-on-repeat)
  invalidAttempts?: number;
  createdAt: number;
  updatedAt: number;
}

export interface CreateReservationRequest {
  businessId: string;
  customerName: string;
  /** Apellido, stored in customers.lastName; optional for legacy/instant flows. */
  customerLastName?: string | null;
  customerPhone: string;
  partySize: number;
  tableId?: string;
  source?: 'AI_CHAT' | 'DASHBOARD';
  /** ISO UTC instant for a future day/time within the next 7 days; omitted/null = instant reservation for the current turn. */
  scheduledAt?: string | null;
  /** Set when the reservation is for one of the business's events. Forces WAITING. */
  eventId?: string | null;
}

export interface CreateReservationResponse {
  success: boolean;
  waitlistEntry?: WaitlistEntry;
  error?: string;
  /** True when a valid reservation already exists for this customer today */
  alreadyExists?: boolean;
  /**
   * Present when creation was rejected by a business-configured date block
   * (business_blocked_dates or future_reservations_blocked_for_date) — a
   * ready-to-send Spanish message for the customer, relayed as-is.
   */
  blockedMessage?: string;
}
